### PR TITLE
Enable html5 routing with history api

### LINKED ISSUE #4: Support html5 routing
Currently does hash routing only. Main reason I didn't *just do it* is that with html5 routing you need to add `onClick` handlers to anchors to intercept - prevent default - and call `pushState` :rose:

The docs mention that currently it only does `#/` routing http://basarat.com/yester/#/?id=what-does-it-support

### PR DESCRIPTION
**Pull request by mattoni**
This PR resolves #4  

Implemented the [history](https://github.com/reacttraining/history) API to enable options like memory routing, html5 routing, hash routing etc via the same API. 

I wasn't sure if this was the direction you wanted to go in, but I'm excited about the possibility of a Typescript-native API and stateful routing that works in any environment. Let me know if there are changes you want to make.

### CODE REVIEW

**Comment by basarat** [comment]
* I've given you github access so you can merge at will and we can discuss afterwards if I have an opinion 👍 
* Would like to keep it *react independent*. So https://github.com/basarat/yester/pull/8/files#diff-0197ac46c78e9a1c7fa4ac64d595bff0R69 can't be in here. Happy to go with this for now till I figure out a better API (my problem) :rose: 
* The prevent default function body should not prevent center clicks and right clicks https://github.com/basarat/yester/pull/8/files#diff-0197ac46c78e9a1c7fa4ac64d595bff0R70 

Can I have your npm name to give you publish access : https://www.npmjs.com/~basarat 

Feel free to do whatever you want with this package and release it as minor `npm version minor`. Just know that when I come back I might refactor the things a bit :rose: :heart:

**Comment by basarat** [comment]
> Can I have your npm name to give you publish access

I've added you https://www.npmjs.com/~amattoni :heart:

**Comment by basarat** [comment]
> Would like to keep it react independent

I was thinking (not the final name but the concept)

```ts
<a onClick={(e) => yester.onAnchorClick(e.nativeEvent)} href={foo} />
```

This way 
* yester can be used with or without react
* allows user to style their anchor and add any additional behaviour they want easily.

**Comment by mattoni** [comment]
@basarat Awesome, happy to help out. 

As for keeping it React independent, I wrote the link component as an example in the demo. Never intended it to go into the API :)  That's an interesting concept as an event handler function. I'll try it out. Going to be working this into a couple of my projects so I'll try and get a feel for that approach. 

So far the only difference with the API is that `navigate` and such need to be part of the Router instance so they can interact with the invocated history object, but your way should work with that as well. 

Anyway, going to write an implementation of this in my project so I can give it a spin. Love the minimalist approach tho. Talk with you when you come out of your cave lol.

**Pull request merged**
