### PR TITLE
Optional initial path for router and the ability to disable trigger in the init function

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by basarat** [comment]
You can just call `navigate` already. Let me know if that doesn't satisfy what you are trying to do :rose:

**Comment by mattoni** [comment]
@basarat I'm working with Alex on an SSR implementation utilizing yester. The challenge is once the server renders the route and returns the HTML, the state should be set, and running the route on the client side after initial load shouldn't be necessary. It can be mitigated by checking the state, but that would need to be done on every route. 

I recommended separating out the init from the initial navigation as a possible solution. Do you have any other ideas?

**Comment by ghost** [comment]
@basarat You are right, I can set the initial route by calling `navigate`, I will revert that commit.  But I still need a way to tell init to not run `trigger` on the initial route.

**Comment by basarat** [comment]
@mattoni I leave it in your safe hands :rose: :heart: 

I can't open the PR for some reason (suspect the branch is deleted). I leave reopening / creating a new one with you as well :heart:

image

**Comment by ghost** [comment]
Haha.  I guess Github is smart enough to know when another PR is created from the same branch.  I already created a new one (#13).

**Pull request closed without merging**
